[log_schema]
host_key = "host"
message_key = "message"
source_type_key = "source_type"
timestamp_key = "timestamp"

# sources for logs\n\n
[sources.custom_logs]
type = "file"
include = ["/var/log/supervisord/*"]
fingerprint.strategy = "device_and_inode"

[sinks.vector_sink]
type = "loki"
inputs = ["custom_logs"]
endpoint = "http://loki.monitoring-system.svc.cluster.local:3100"

[sinks.vector_sink.encoding]
codec = "json"

[sinks.vector_sink.labels]
name = "jeeves_custom_logs_<<tenant>>"

[transforms.jeeves_kubernetes_logs_filter]
type = "filter"
inputs = ["custom_logs"]
condition = 'contains(string!(.file), "stderr")'

[transforms.jeeves_kubernetes_logs_decode]
type = "remap"
inputs = ["jeeves_kubernetes_logs_filter"]
source = '''
.channel = "C04J9J9NH6X"

. |= parse_regex!(.message, r'.*time=(?P<time>[^ ]*)\s*.*loglevel=(?P<level>.*).*filename=(?P<filename>.*).*message=(?P<message>.*).*traceID=(?P<traceID>.*).*spanID=(?P<spanID>.*)')
if !exists(.time) || !exists(.level) {
  abort
}
.text = join!([
  "{\"",
  "type\":\"Worker\",",
  "\"time\":\"", .time,"\",",
  "\"loglevel\":\"", .level,"\",",
  "\"filename\":\"", .filename,"\",",
  "\"message\":", .message,",",
  "\"traceID\":\"", .traceID,"\",",
  "\"spanID\":\"", .spanID,"\",",
  "\"tenant\":\"<<tenant>>\"}"
])
'''

[transforms.jeeves_kubernetes_logs_all]
type = "filter"
inputs = ["jeeves_kubernetes_logs_decode"]
condition = 'contains(string!(.level), "ERROR")'

[sinks.jeeves_kubernetes_logs_decode_out]
type = "http"
inputs = ["jeeves_kubernetes_logs_all"]
uri = "https://vector-slack-http-sink.314e.workers.dev/"
method = "post"

[sinks.jeeves_kubernetes_logs_decode_out.request.headers]
Authorization = "{{ op://314e DevOps/Application/slack_bearer_token_vector_toml }}"

[sinks.jeeves_kubernetes_logs_decode_out.encoding]
codec = "json"