[r2]
type = s3
provider = Cloudflare
access_key_id = {{ open_brackets }}op://Jeeves/application-config/INTEGRATION_COMMON_CONFIG/r2_access_key{{ close_brackets }}
secret_access_key = {{ open_brackets }}op://Jeeves/application-config/INTEGRATION_COMMON_CONFIG/r2_secret_key{{ close_brackets }}
region = auto
endpoint = https://4b92451476ed49bcf987231b504ca149.r2.cloudflarestorage.com
acl = private