[r2]
type = s3
provider = Cloudflare
access_key_id = {{ op://Jeeves/application-config/PRODUCTION_COMMON_CONFIG/r2_access_key }}
secret_access_key = {{ op://Jeeves/application-config/PRODUCTION_COMMON_CONFIG/r2_secret_key }}
region = auto
endpoint = https://4b92451476ed49bcf987231b504ca149.r2.cloudflarestorage.com
acl = private