datasources:
    postgres:
      url: jdbc:postgresql://db-cluster-ha.postgresql.svc.cluster.local:5432/kestra_<<tenant>> 
      driverClassName: org.postgresql.Driver
      username: kestra_<<tenant>>
      password: {{ op://hdp/application-config/hdp_<<tenant>>/kestra_pg_password }}
      schema: hdpcqm
kestra:
  server:
    basic-auth:
      enabled: true
      username: kestra@314ecorp.com
      password: {{op://hdp/application-config/hdp_<<tenant>>/kestra_password}}
  repository:
    type: postgres
  storage:
    type: local
    local:
      base-path: "/app/storage"
  queue:
    type: postgres
  tasks:
    tmp-dir:
      path: /tmp/kestra-wd/tmp
  url: http://0.0.0.0:18080/
  plugins:
    configurations:
      - type: io.kestra.plugin.scripts.runner.docker.Docker
        values:
          volume-enabled: true