{
 "title": "<<dynamic_variable_tenant>> - Spring Boot 3.x Statistics",
 "description": "Spring Boot Dashboard adapted from https://grafana.com/grafana/dashboards/10280-microservices-spring-boot-2-1/",
 "tags": [ "app" ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "application",
    "label": "Application",
    "query": {
     "query": "label_values(jvm_info,application_server)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "query_result((up{namespace=\"<<dynamic_variable_tenant>>\", container=\"$application\"} == 1))"
    }
   },
   {
    "name": "memory_pool_heap",
    "label": "Memory Pool (heap)",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{instance=\"$instance\", area=\"heap\", application_server=\"$application\"},id)"
    }
   },
   {
    "name": "memory_pool_nonheap",
    "label": "Memory Pool (nonheap)",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{instance=\"$instance\", area=\"nonheap\", application_server=\"$application\"},id)"
    }
   },
   {
    "name": "hikaricp",
    "query": {
     "query": "label_values(hikaricp_connections{application_server=\"$application\", instance=\"$instance\", namespace=\"<<dynamic_variable_tenant>>\"},pool)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Basic Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{application_server=\"$application\", instance=\"$instance\", namespace=\"<<dynamic_variable_tenant>>\"}"
    }
   ]
  },
  {
   "title": "Heap Used",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application_server=\"$application\", instance=\"$instance\", area=\"heap\", namespace=\"<<dynamic_variable_tenant>>\"})*100/sum(jvm_memory_max_bytes{application_server=\"$application\",instance=\"$instance\", area=\"heap\", namespace=\"<<dynamic_variable_tenant>>\"})"
    }
   ]
  },
  {
   "title": "Non-Heap Used",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application_server=\"$application\", instance=\"$instance\", area=\"nonheap\", namespace=\"<<dynamic_variable_tenant>>\"})*100/sum(jvm_memory_max_bytes{application_server=\"$application\",instance=\"$instance\", area=\"nonheap\", namespace=\"<<dynamic_variable_tenant>>\"})"
    }
   ]
  },
  {
   "title": "Process Open Files",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "process_files_open_files{application_server=\"$application\", instance=\"$instance\", namespace=\"<<dynamic_variable_tenant>>\"}",
     "legendFormat": "Open Files"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{application_server=\"$application\", instance=\"$instance\", namespace=\"<<dynamic_variable_tenant>>\"}*1000"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "system_cpu_usage{instance=\"$instance\", application_server=\"$application\", namespace=\"<<dynamic_variable_tenant>>\"}",
     "legendFormat": "System CPU Usage"
    },
    {
     "expr": "process_cpu_usage{instance=\"$instance\", application_server=\"$application\", namespace=\"<<dynamic_variable_tenant>>\"}",
     "legendFormat": "Process CPU Usage"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "system_load_average_1m{instance=\"$instance\", application_server=\"$application\", namespace=\"<<dynamic_variable_tenant>>\"}",
     "legendFormat": "Load Average [1m]"
    },
    {
     "expr": "system_cpu_count{instance=\"$instance\", application_server=\"$application\", namespace=\"<<dynamic_variable_tenant>>\"}",
     "legendFormat": "CPU Core Size"
    }
   ]
  },
  {
   "title": "JVM Statistics - Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {}
   ]
  },
  {
   "title": "$memory_pool_heap (heap)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 },
   "repeat": "memory_pool_heap",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{instance=\"$instance\", id=\"$memory_pool_heap\", namespace=\"<<dynamic_variable_tenant>>\", application_server=\"$application\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_committed_bytes{instance=\"$instance\", id=\"$memory_pool_heap\", namespace=\"<<dynamic_variable_tenant>>\", application_server=\"$application\"}",
     "legendFormat": "Commited"
    },
    {
     "expr": "jvm_memory_max_bytes{instance=\"$instance\", application_server=\"$application\", id=\"$memory_pool_heap\", namespace=\"<<dynamic_variable_tenant>>\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "$memory_pool_nonheap (non-heap)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 23 },
   "repeat": "memory_pool_nonheap",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{instance=\"$instance\", application_server=\"$application\", id=\"${memory_pool_nonheap:raw}\", namespace=\"<<dynamic_variable_tenant>>\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_committed_bytes{instance=\"$instance\", application_server=\"$application\", id=\"${memory_pool_nonheap:raw}\", namespace=\"<<dynamic_variable_tenant>>\"}",
     "legendFormat": "Commited"
    },
    {
     "expr": "jvm_memory_max_bytes{instance=\"$instance\", application_server=\"$application\", id=\"${memory_pool_nonheap:raw}\", namespace=\"<<dynamic_variable_tenant>>\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_threads_daemon_threads{instance=\"$instance\", application_server=\"$application\", namespace=\"<<dynamic_variable_tenant>>\"}",
     "legendFormat": "Daemon"
    },
    {
     "expr": "jvm_threads_live_threads{instance=\"$instance\", application_server=\"$application\", namespace=\"<<dynamic_variable_tenant>>\"}",
     "legendFormat": "Live"
    },
    {
     "expr": "jvm_threads_peak_threads{instance=\"$instance\", application_server=\"$application\", namespace=\"<<dynamic_variable_tenant>>\"}",
     "legendFormat": "Peak"
    }
   ]
  },
  {
   "title": "Direct Buffers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_buffer_memory_used_bytes{instance=\"$instance\", application_server=\"$application\", id=\"direct\", namespace=\"<<dynamic_variable_tenant>>\"}",
     "legendFormat": "Used Bytes"
    },
    {
     "expr": "jvm_buffer_total_capacity_bytes{instance=\"$instance\", application_server=\"$application\", id=\"direct\", namespace=\"<<dynamic_variable_tenant>>\"}",
     "legendFormat": "Capacity Bytes"
    }
   ]
  },
  {
   "title": "Mapped Buffers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_buffer_memory_used_bytes{instance=\"$instance\", application_server=\"$application\", id=\"mapped\", namespace=\"<<dynamic_variable_tenant>>\"}",
     "legendFormat": "Used Bytes"
    },
    {
     "expr": "jvm_buffer_total_capacity_bytes{instance=\"$instance\", application_server=\"$application\", id=\"mapped\", namespace=\"<<dynamic_variable_tenant>>\"}",
     "legendFormat": "Capacity Bytes"
    }
   ]
  },
  {
   "title": "Memory Allocate/Promote",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "irate(jvm_gc_memory_allocated_bytes_total{instance=\"$instance\", application_server=\"$application\", namespace=\"<<dynamic_variable_tenant>>\"}[$__rate_interval])",
     "legendFormat": "allocated"
    },
    {
     "expr": "irate(jvm_gc_memory_promoted_bytes_total{instance=\"$instance\", application_server=\"$application\", namespace=\"<<dynamic_variable_tenant>>\"}[$__rate_interval])",
     "legendFormat": "promoted"
    }
   ]
  },
  {
   "title": "JVM Statistics - GC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "targets": [
    {}
   ]
  },
  {
   "title": "GC Count",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "irate(jvm_gc_pause_seconds_count{instance=\"$instance\", application_server=\"$application\", namespace=\"<<dynamic_variable_tenant>>\"}[$__rate_interval])",
     "legendFormat": "{{action}} [{{cause}}]"
    }
   ]
  },
  {
   "title": "GC Stop the World Duration",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(jvm_gc_pause_seconds_sum{instance=\"$instance\", application_server=\"$application\", namespace=\"<<dynamic_variable_tenant>>\"}[$__rate_interval])",
     "legendFormat": "{{action}} [{{cause}}]"
    }
   ]
  },
  {
   "title": "Database Connection Pool HikariCP  Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Connections Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hikaricp_connections{instance=\"$instance\", application_server=\"$application\", namespace=\"<<dynamic_variable_tenant>>\"}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "hikaricp_connections_active{instance=\"$instance\", application_server=\"$application\", pool=\"$hikaricp\", namespace=\"<<dynamic_variable_tenant>>\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "hikaricp_connections_idle{instance=\"$instance\", application=\"$application\", pool=\"$hikaricp\", namespace=\"<<dynamic_variable_tenant>>\"}",
     "legendFormat": "Idle"
    },
    {
     "expr": "hikaricp_connections_pending{instance=\"$instance\", application=\"$application\", pool=\"$hikaricp\", namespace=\"<<dynamic_variable_tenant>>\"}",
     "legendFormat": "Pending"
    }
   ]
  },
  {
   "title": "Connection Timeout Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hikaricp_connections_timeout_total{instance=\"$instance\", application_server=\"$application\", pool=\"$hikaricp\", namespace=\"<<dynamic_variable_tenant>>\"}"
    }
   ]
  },
  {
   "title": "Connection Creation Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "hikaricp_connections_creation_seconds_sum{instance=\"$instance\", application_server=\"$application\", pool=\"$hikaricp\"} / hikaricp_connections_creation_seconds_count{instance=\"$instance\", application_server=\"$application\", pool=\"$hikaricp\"}",
     "legendFormat": "Creation Time"
    }
   ]
  },
  {
   "title": "Connection Usage Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "hikaricp_connections_usage_seconds_sum{instance=\"$instance\", application_server=\"$application\", pool=\"$hikaricp\"} / hikaricp_connections_usage_seconds_count{instance=\"$instance\", application_server=\"$application\", pool=\"$hikaricp\"}",
     "legendFormat": "Usage Time"
    }
   ]
  },
  {
   "title": "Connection Acquire Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "hikaricp_connections_acquire_seconds_sum{instance=\"$instance\", application_server=\"$application\", pool=\"$hikaricp\"} / hikaricp_connections_acquire_seconds_count{instance=\"$instance\", application_server=\"$application\", pool=\"$hikaricp\"}",
     "legendFormat": "Acquire Time"
    }
   ]
  },
  {
   "title": "Logback Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 },
   "targets": [
    {}
   ]
  },
  {
   "title": "INFO logs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(logback_events_total{instance=\"$instance\", application_server=\"$application\", level=\"info\", namespace=\"<<dynamic_variable_tenant>>\"}[$__rate_interval])",
     "legendFormat": "info",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "ERROR logs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(logback_events_total{instance=\"$instance\", application_server=\"$application\", level=\"error\", namespace=\"<<dynamic_variable_tenant>>\"}[$__rate_interval])",
     "legendFormat": "error",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "WARN logs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(logback_events_total{instance=\"$instance\", application_server=\"$application\", level=\"warn\", namespace=\"<<dynamic_variable_tenant>>\"}[$__rate_interval])",
     "legendFormat": "warn",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "DEBUG logs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(logback_events_total{instance=\"$instance\", application_server=\"$application\", level=\"debug\", namespace=\"<<dynamic_variable_tenant>>\"}[$__rate_interval])",
     "legendFormat": "debug",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "TRACE logs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(logback_events_total{instance=\"$instance\", application_server=\"$application\", level=\"trace\", namespace=\"<<dynamic_variable_tenant>>\"}[$__rate_interval])",
     "legendFormat": "trace",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  }
 ]
}