{
 "title": "<<dynamic_variable_tenant>> - Apache Camel - Context view",
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "interface",
    "label": "Camel Interface",
    "query": {
     "query": "label_values(zsegment_messages_inbound_total{tenant=\"<<dynamic_variable_tenant>>\"},interface_name)"
    }
   },
   {
    "name": "route",
    "label": "Camel Route",
    "query": {
     "query": "label_values(zsegment_messages_inbound_total{tenant=\"<<dynamic_variable_tenant>>\", interface_name=\"$interface\"},route_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Stats for interface: [$interface]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Inbound messages for interface: [$interface]",
   "type": "timeseries",
   "description": "Shows completed exchanges of the camel context in the time range for given interface",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(\n    increase(\n        zsegment_messages_inbound_total{\n            tenant=\"<<dynamic_variable_tenant>>\",\n            interface_name=\"$interface\"\n        }[$__range]\n    )\n)",
     "legendFormat": "Total messages"
    }
   ]
  },
  {
   "title": "Success for interface: [$interface]",
   "type": "stat",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (\n    increase(\n        zsegment_messages_success_total{\n            tenant=\"<<dynamic_variable_tenant>>\",\n            interface_name=\"$interface\"\n        }[$__range]\n    )\n)",
     "legendFormat": "Total success"
    },
    {
     "expr": "sum (\n    increase(\n        zsegment_messages_success_total{\n            tenant=\"<<dynamic_variable_tenant>>\",\n            interface_name=\"$interface\"\n        }[$__range])\n    ) \n/ \nsum (\n    increase(\n        zsegment_messages_inbound_total{\n            tenant=\"<<dynamic_variable_tenant>>\",\n            interface_name=\"$interface\"\n        }[$__range]\n    )\n)*100",
     "legendFormat": "Success %"
    }
   ]
  },
  {
   "title": "Avg Exec time for interface: [$interface]",
   "type": "stat",
   "description": "Average execution time for an interface",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (interface_name) (sum_over_time(zsegment_message_processing_time{tenant=\"<<dynamic_variable_tenant>>\", interface_name=\"$interface\"}[$__range])\n)\n/ sum by (interface_name) (count_over_time(zsegment_message_processing_time{tenant=\"<<dynamic_variable_tenant>>\", interface_name=\"$interface\"}[$__range]))",
     "legendFormat": "Avg exec time"
    }
   ]
  },
  {
   "title": "Failures for interface: [$interface]",
   "type": "stat",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (\n    increase(\n        zsegment_messages_failure_total{\n            tenant=\"<<dynamic_variable_tenant>>\",\n            interface_name=\"$interface\"\n        }[$__range]\n    )\n)",
     "legendFormat": "Total failures"
    },
    {
     "expr": "sum (\n    increase(\n        zsegment_messages_failure_total{\n            tenant=\"<<dynamic_variable_tenant>>\",\n            interface_name=\"$interface\"\n        }[$__range])\n    ) \n/ \nsum (\n    increase(\n        zsegment_messages_inbound_total{\n            tenant=\"<<dynamic_variable_tenant>>\",\n            interface_name=\"$interface\"\n        }[$__range]\n    )\n)*100",
     "legendFormat": "Failure %"
    }
   ]
  },
  { "title": "Stats for route: [$route]", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Inbound messages for route: [$route]",
   "type": "timeseries",
   "description": "Shows completed exchanges of the camel context in the time range for given route",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(\n    increase(\n        zsegment_messages_inbound_total{\n            tenant=\"<<dynamic_variable_tenant>>\",\n            interface_name=\"$interface\",\n            route_id=\"$route\"\n        }[$__range]\n    )\n)",
     "legendFormat": "Total messages"
    }
   ]
  },
  {
   "title": "Success for route: [$route]",
   "type": "stat",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (\n    increase(\n        zsegment_messages_success_total{\n            tenant=\"<<dynamic_variable_tenant>>\",\n            interface_name=\"$interface\",\n            route_id=\"$route\"\n        }[$__range]\n    )\n)",
     "legendFormat": "Total success"
    },
    {
     "expr": "sum (\n    increase(\n        zsegment_messages_success_total{\n            tenant=\"<<dynamic_variable_tenant>>\",\n            interface_name=\"$interface\",\n            route_id=\"$route\"\n        }[$__range])\n    ) \n/ \nsum (\n    increase(\n        zsegment_messages_inbound_total{\n            tenant=\"<<dynamic_variable_tenant>>\",\n            interface_name=\"$interface\",\n            route_id=\"$route\"\n        }[$__range]\n    )\n)*100",
     "legendFormat": "Success %"
    }
   ]
  },
  {
   "title": "Avg Exec time for route:  [$route]",
   "type": "stat",
   "description": "Average execution time for a route",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 20 },
   "repeat": "route",
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (route_id) (sum_over_time(zsegment_message_processing_time{tenant=\"<<dynamic_variable_tenant>>\", interface_name=\"$interface\", route_id=\"$route\"}[$__range])\n)\n/ sum by (route_id) (count_over_time(zsegment_message_processing_time{tenant=\"<<dynamic_variable_tenant>>\", interface_name=\"$interface\", route_id=\"$route\"}[$__range]))",
     "legendFormat": "Avg exec time"
    }
   ]
  },
  {
   "title": "Failures for route: [$route]",
   "type": "stat",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (\n    increase(\n        zsegment_messages_failure_total{\n            tenant=\"<<dynamic_variable_tenant>>\",\n            interface_name=\"$interface\",\n            route_id=\"$route\"\n        }[$__range]\n    )\n)",
     "legendFormat": "Total failures"
    },
    {
     "expr": "sum (\n    increase(\n        zsegment_messages_failure_total{\n            tenant=\"<<dynamic_variable_tenant>>\",\n            interface_name=\"$interface\",\n            route_id=\"$route\"\n        }[$__range])\n    ) \n/ \nsum (\n    increase(\n        zsegment_messages_inbound_total{\n            tenant=\"<<dynamic_variable_tenant>>\",\n            interface_name=\"$interface\",\n            route_id=\"$route\"\n        }[$__range]\n    )\n)*100",
     "legendFormat": "Failure %"
    }
   ]
  },
  {
   "title": "Interface [$interface] Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 }
  },
  {
   "title": "Duration : Avg Execution time in routes",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (route_id) (sum_over_time(zsegment_message_processing_time{tenant=\"<<dynamic_variable_tenant>>\", interface_name=\"$interface\"}[$__range])\n)\n/ sum by (route_id) (count_over_time(zsegment_message_processing_time{tenant=\"<<dynamic_variable_tenant>>\", interface_name=\"$interface\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors : Failure Rates in routes",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (route_id) (\n    increase(\n        zsegment_messages_failure_total{\n            tenant=\"<<dynamic_variable_tenant>>\",\n            interface_name=\"$interface\",\n        }[$__range]\n    )\n) \n/ \nsum by (route_id) (\n    increase(\n        zsegment_messages_inbound_total{\n            tenant=\"<<dynamic_variable_tenant>>\",\n            interface_name=\"$interface\"\n        }[$__range]\n    ) > 0\n)",
     "legendFormat": "{{routeId}}"
    }
   ]
  }
 ]
}