FROM python:3.13.1-slim

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get -qq update && \
  apt-get install --no-install-recommends -y apt-transport-https build-essential ca-certificates \
  openssh-server rsync sshfs supervisor vim && \
  rm -rf /var/lib/apt/lists/*

ADD https://cache.agilebits.com/dist/1P/op2/pkg/v2.29.0/op_linux_amd64_v2.29.0.zip /tmp/op.zip
ADD https://dl.min.io/client/mc/release/linux-amd64/mc /tmp/mc
ADD https://github.com/just-containers/s6-overlay/releases/download/v2.2.0.3/s6-overlay-amd64.tar.gz \
    /tmp/s6-overlay-amd64.tar.gz

RUN \
    # install vector
    bash /tmp/setup/vector.deb.sh && \
    apt-get update && \
    apt-get install -y vector && \
    rm -f /tmp/setup/vector.deb.sh && \
    # install unzip
    apt-get install --no-install-recommends -y unzip && \
    # install op
    unzip -d op /tmp/op.zip && \
    mv op/op /usr/local/bin/ && \
    rm -rf /tmp/op.zip op && \
    # install mc
    mv /tmp/mc /bin/ && chmod +x /bin/mc && \
    # install nodejs
    apt-get install --no-install-recommends -y nodejs npm && \
    apt-get clean && \
    npm install npm@9 -g && \
    npm install n -g wrangler postcss-cli && \
    n latest && \
    rm -rf /var/lib/apt/lists/* && \
    # install s6 overlay
    mkdir /tmp/s6/ && \
    tar xzf /tmp/s6-overlay-amd64.tar.gz -C /tmp/s6/ && \
    rm -f /tmp/s6-overlay-amd64.tar.gz &&  \
    rsync -aq --ignore-existing --remove-source-files /tmp/s6/ /

