sonar.organization=softwareartistry
sonar.projectKey=softwareartistry_launchpad-app_4a27a4fa-5ad5-4084-abb4-79eff80a145c
sonar.python.version=3.11.9
# ignore the following files
sonar.exclusions=.gitignore,Dockerfile,Dockerfile.base,app/exception/error_codes_en.py