[minio]
type = s3
provider = Minio
env_auth = false
access_key_id = ostoreconsole
secret_access_key = {{ open_brackets }}op://Jeeves/application-config/INTEGRATION_COMMON_CONFIG/ostore_secret_key{{ close_brackets }}
region = us-east-1
endpoint = https://ostore.314ecorp.tech
location_constraint =
server_side_encryption =