[request_definition]
r = role, resource, method

[policy_definition]
p = role, resource, method

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = (r.method == p.method) && \
    routeMatch(r.resource, p.resource) && \
    roleMatch(r.role, p.role)
