; ==================================
; celery worker supervisor
; info about options - http://supervisord.org/configuration.html#program-x-section-settings
; ==================================
; ==================================
; cli worker supervisor
; info about options - http://supervisord.org/configuration.html#program-x-section-settings
; ==================================


[program:temporal_jeeves_onboarding_worker]
    directory=/app
    command=python3 app/cli/temporal/jeeves/workers/onboarding.py
    autostart=true
    autorestart=true
    startsecs=10
    stopwaitsecs=600
    stopasgroup=true
    priority=1000

[program:temporal_jeeves_deprovisioning_worker]
    directory=/app
    command=python3 app/cli/temporal/jeeves/workers/deprovisioning.py
    autostart=true
    autorestart=true
    startsecs=10
    stopwaitsecs=600
    stopasgroup=true
    priority=1000

[program:temporal_veritable_onboarding_worker]
    directory=/app
    command=python3 app/cli/temporal/veritable/workers/onboarding.py
    autostart=true
    autorestart=true
    startsecs=10
    stopwaitsecs=600
    stopasgroup=true
    priority=1000


[program:temporal_veritable_deprovisioning_worker]
    directory=/app
    command=python3 app/cli/temporal/veritable/workers/deprovisioning.py
    autostart=true
    autorestart=true
    startsecs=10
    stopwaitsecs=600
    stopasgroup=true
    priority=1000

[program:temporal_dexit_onboarding_worker]
    directory=/app
    command=python3 app/cli/temporal/dexit/workers/onboarding.py
    autostart=true
    autorestart=true
    startsecs=10
    stopwaitsecs=600
    stopasgroup=true
    priority=1000

[program:temporal_dexit_deprovisioning_worker]
    directory=/app
    command=python3 app/cli/temporal/dexit/workers/deprovisioning.py
    autostart=true
    autorestart=true
    startsecs=10
    stopwaitsecs=600
    stopasgroup=true
    priority=1000

[program:temporal_penknife_onboarding_worker]
    directory=/app
    command=python3 app/cli/temporal/penknife/workers/onboarding.py
    autostart=true
    autorestart=true
    startsecs=10
    stopwaitsecs=600
    stopasgroup=true
    priority=1000

[program:temporal_penknife_deprovisioning_worker]
    directory=/app
    command=python3 app/cli/temporal/penknife/workers/deprovisioning.py
    autostart=true
    autorestart=true
    startsecs=10
    stopwaitsecs=600
    stopasgroup=true
    priority=1000

[program:temporal_hdp_onboarding_worker]
    directory=/app
    command=python3 app/cli/temporal/hdp/workers/onboarding.py
    autostart=true
    autorestart=true
    startsecs=10
    stopwaitsecs=600
    stopasgroup=true
    priority=1000


[program:temporal_zsegment_onboarding_worker]
    directory=/app
    command=python3 app/cli/temporal/zsegment/workers/onboarding.py
    autostart=true
    autorestart=true
    startsecs=10
    stopwaitsecs=600
    stopasgroup=true
    priority=1000


[program:temporal_practifly_onboarding_worker]
    directory=/app
    command=python3 app/cli/temporal/practifly/workers/onboarding.py
    autostart=true
    autorestart=true
    startsecs=10
    stopwaitsecs=600
    stopasgroup=true
    priority=1000
