[app]
name = "pricedx"
tenant = "<<tenant>>"

[server]
host = "0.0.0.0:8000"
parallelism_factor = 10
temp_path = "/tmp"
allowed_origin = [
    "https://<<tenant>>.pricedx.tech",
]

[keycloak]
realm = "<<tenant>>"
auth_url = "{{ op://Pricedx/application-config/INTEGRATION_COMMON_CONFIG/keycloak_auth_url }}"
client_id = "{{ op://Pricedx/application-config/INTEGRATION_COMMON_CONFIG/keycloak_client_id }}"

[redis]
dsn = "{{ op://Pricedx/application-config/PRICEDX_<<tenant>>/redis_dsn }}"
password = "{{ op://Pricedx/application-config/PRICEDX_<<tenant>>/redis_password }}"

[postgres]
dsn = "{{ op://Pricedx/application-config/PRICEDX_<<tenant>>/pg_dsn }}"
schema_name = "{{ op://Pricedx/application-config/PRICEDX_<<tenant>>/pg_schema_name }}"

[starrocks]
catalog = "{{ op://Pricedx/application-config/INTEGRATION_COMMON_CONFIG/starrocks_catalog }}"
conn_string = "{{ op://Pricedx/application-config/INTEGRATION_COMMON_CONFIG/starrocks_conn_string }}"
