kind: Deployment
metadata:
  name: veritable-cli
  namespace: default
  spec:
    replicas: {{replica}}
    selector:
      matchLabels:
        app: veritable-cli
    template:
      metadata:
        labels:
          app: veritable-cli
        spec:
            image_pull_secrets:
              name: registrycred
            node_selector:
              app: 314e
            containers:
              name: veritable
              image: registry.314ecorp.tech/{{image_tag}}
              resources:
                requests:
                  memory: {{request["memory"]}}
                  cpu: {{request["cpu"]}}
                limits:
                  memory: {{limit["memory"]}}
                  cpu: {{limit["cpu"]}}
              ports:
                name: http
                protocol: TCP
                containerPort: {{container_port}}
              imagePullPolicy: Always
              volumeMounts:
                - name: env-volume
                  mountPath: /config/env-config.json
                  subPath: env-config.json
                - name: tenant-volume
                  mountPath: /config/tenant-config.json
                  subPath: tenant-config.json
                - name: vector-volume
                  mountPath: /vector
                  readOnly: true
                - name: veritable-pvc
                  mountPath: /data
                  readOnly: false
              env:
                - name: DEPLOYMENT
                  value: {{env}}
                - name: POSTGRES__PASSWORD
                  value: {{postgres_password}}
                - name: POSTGRES__USER
                  value: {{postgres_user}}
                - name: RELEASE_VERSION
                  value: {{new_image_tag}}
                - name: APP_CONFIG_DIR
                  value: /config
                - name: CLIENT_CODE
                  value: {{tenant}}
                - name: IS_CLI
                  value: "TRUE"
                - name: ORG_NAME
                  value: {{org_name}}
            volumes:
              - name: env-volume
                configMap:
                  name: veritable-env-config
                  items:
                    - key: env-config.json
                      path: env-config.json
              - name: tenant-volume
                configMap:
                  name: veritable-tenant-config
                  items:
                    - key: tenant-config.json
                      path: tenant-config.json
              - name: vector-volume
                configMap:
                  name: veritable-cli-vector-config
                  items:
                    - key: vector-config.toml
                      path: vector-config.toml
              - name: veritable-pvc
                persistentVolumeClaim:
                  claimName: veritable-pvc
