apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: veritable-vs
  namespace: {{tenant}}
spec:
  hosts:
    - {{tenant}}.{{domain_name}}
  gateways:
    - istio-system/istiogateway
  http:
    - name: veritable-api
      route:
        - destination:
            host: veritable.{{tenant}}.svc.cluster.local
            port:
              number: 8000
            headers:
              response:
                set:
                  - name: Strict-Transport-Security
                    value: max-age=31536000;includeSubDomains;preload
      match:
        - uri:
            regex: ^/api/v1/.*
        - uri:
            regex: ^/public/api/v1/.*
        - uri:
            prefix: /docs
        - uri:
            prefix: /redoc

    {% if environment != "production" -%}
    - name: redirect
      match:
        - uri:
            exact: /
      redirect:
        uri: /{{image_tag}}/
    {% endif %}

    - name: veritable-ui
      route:
        - destination:
            host: varnish-svc.varnish.svc.cluster.local
            port:
              number: 80
      match:
        - uri:
            prefix: /
