apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  labels:
    scaledobject.keda.sh/name: veritable-autoscaler
  name: veritable-autoscaler
  namespace: <<tenant>>
spec:
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          policies:
          - periodSeconds: 90
            type: Pods
            value: 1
          stabilizationWindowSeconds: 300
        scaleUp:
          policies:
          - periodSeconds: 30
            type: Pods
            value: 1
          stabilizationWindowSeconds: 0
    scalingModifiers: {}
  maxReplicaCount: 4
  minReplicaCount: 2
  pollingInterval: 15
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: veritable
  triggers:
  - metadata:
      activationThreshold: "10"
      metricName: starlette_requests_in_progress_per_replica_avg
      query: avg_over_time(sum(starlette_requests_in_progress{path_template!="/metrics/", namespace="<<tenant>>", job="<<tenant>>/veritable-metrics"})[2m]) / (sum(kube_deployment_status_replicas{deployment="veritable", exported_namespace="<<tenant>>"}) or 1)
      serverAddress: http://vmselect-vm-cluster.monitoring-system.svc.cluster.local:8481/select/0/prometheus
      threshold: "15"
    metricType: Value
    type: prometheus
