apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: veritable-worker-critical-autoscaler
  namespace: <<tenant>>
spec:
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          policies:
          - periodSeconds: 90
            type: Pods
            value: 1
          stabilizationWindowSeconds: 300
        scaleUp:
          policies:
          - periodSeconds: 15
            type: Pods
            value: 2
          stabilizationWindowSeconds: 0
    scalingModifiers: {}
  maxReplicaCount: 3
  minReplicaCount: 1
  pollingInterval: 10
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: veritable-worker-critical
  triggers:
  - metadata:
      activationThreshold: "10"
      metricName: approximate_backlog_count
      query: sum(approximate_backlog_count{exported_namespace="veritable_<<tenant>>", taskqueue="CRITICAL"})
      serverAddress: http://vmselect-vmcluster.monitoring-system.svc.cluster.local:8481/select/0/prometheus
      threshold: "10"
    metricType: Value
    type: prometheus
