name: "Build Launchpad App"

on:
  workflow_dispatch:
  push:
    branches: ["production", "development"]
    paths-ignore:
        - ".github/workflows/**"
  pull_request:
    branches: ["sprint", "production", "development"]

jobs:
  build:
    name: Build
    runs-on: [self-hosted, python3.9]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Ruff
        run: pip install ruff

      - name: Run Ruff
        run: ruff check .

      - name: Install Bandit
        run: pip install bandit[toml]

      - name: Run Bandit
        run: bandit -c pyproject.toml -r -ll .

      - name: OSV Scanner
        run: osv-scanner --lockfile=poetry.lock --config=osv-scanner.config.toml

      - name: Build & push the Docker image
        run: |
          chmod +x docker-build.sh
          ./docker-build.sh ${{ github.ref_name }}
