name: "Build Launchpad App"

on:
  workflow_dispatch:
  push:
    branches: ["sprint", "production", "development"]
    paths-ignore:
        - ".github/workflows/**"

jobs:
  build:
    name: Build
    runs-on: [self-hosted, python3.9]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install Ruff
        run: pip install ruff

      - name: Run Ruff
        run: ruff check .

      - name: Install Bandit
        run: pip install bandit

      - name: Run Bandit
        run: bandit -c pyproject.toml -r -ll

      - name: OSV Scanner
        run: osv-scanner --lockfile=poetry.lock --config=osv-scanner.config.toml

      - name: Build the Docker image
        run: |
          docker build . --file Dockerfile --tag registry.314ecorp.tech/launchpad-app:${{ github.ref_name }}

      - name: Push the Docker image
        run: |
          docker push registry.314ecorp.tech/launchpad-app:${{ github.ref_name }}
          docker image prune -f
