name: "Build And Deploy Launchpad App"

on:
  workflow_dispatch:
  push:
    branches: ["sprint", "production", "development"]
    paths-ignore:
        - ".github/workflows/**"

jobs:
  build:
    name: Build
    runs-on: [self-hosted, python3.9]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Ruff
        run: pip install ruff

      - name: Run Ruff
        run: ruff check .

      - name: Install Bandit
        run: pip install bandit[toml]

      - name: Run Bandit
        run: bandit -c pyproject.toml -r -ll .

      - name: OSV Scanner
        run: osv-scanner --lockfile=poetry.lock --config=osv-scanner.config.toml

      - name: Build & push the Docker image
        run: |
          ./docker-build.sh ${{ github.ref_name }} --push

      - name: Deploy to Kubernetes
        if: github.ref_name == 'sprint'
        run: |
          kubectl rollout restart deployment launchpad -n launchpad
          kubectl rollout restart deployment launchpad-cli -n launchpad
