name: "Deploy Onboarding App"

on:
  workflow_run:
    workflows: [ "Build Onboarding App" ]
    branches: [ "sprint" ]
    types:
      - completed

jobs:
  deploy:
    name: Deploy to Kubernetes
    runs-on: [self-hosted, python3.9]
    steps:
      - name: Deploy to Kubernetes SPRINT
        if: github.ref_name == 'sprint'
        run: |
          kubectl rollout restart deployment onboarding-app -n onboarding
          kubectl rollout restart deployment onboarding-cli -n onboarding
