name: "Upload Packages to Nexus"

on:
  workflow_dispatch:
  push:
    branches: ["sprint", "production"]

jobs:
  build:
    name: Build
    runs-on: [self-hosted, python3.9]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install twine
        run: pip install twine

      - name: Build the package
        run: pip download -r requirements.txt -d dist

      - name: Upload the package
        run: twine upload --repository-url https://NEXUS_USERNAME:NEXUS_PASSWORD@artifact.314ecorp.tech/repository/launchpad/ dist/*
