variables:
  payload: {
    product: "veritable",
    tenant: "onboarding",
  }
  arg1: "arg1"

root:
  sequence:
    elements:
      - activity:
          name: postgres_setup_activity
          arguments:
            - payload
      - activity:
          name: keycloak_setup_activity
          arguments:
            - arg1
          result: result2